services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3308:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - clinic-network

  user-service:
    build:
      context: ./services/user-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - clinic-network

volumes:
  mysqldata:

networks:
  clinic-network: