server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/users/**

        - id: user-service-specialities
          uri: http://user-service:8082
          predicates:
            - Path=/specialities/**

        - id: appointment-service
          uri: http://appointment-service:8083
          predicates:
            - Path=/appointments/**

        - id: appointment-service-feedback
          uri: http://appointment-service:8083
          predicates:
            - Path=/feedback/**

        - id: appointment-service-schedules
          uri: http://appointment-service:8083
          predicates:
            - Path=/schedules/**

        - id: appointment-service-surveys
          uri: http://appointment-service:8083
          predicates:
            - Path=/surveys/**

management:
  endpoints:
    web:
      exposure:
        include: health, info