server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**

        - id: user-service-specialities
          uri: http://localhost:8082
          predicates:
            - Path=/specialities/**

        - id: appointment-service
          uri: http://localhost:8083
          predicates:
            - Path=/appointments/**

        - id: appointment-service-feedback
          uri: http://localhost:8083
          predicates:
            - Path=/feedback/**

        - id: appointment-service-schedules
          uri: http://localhost:8083
          predicates:
            - Path=/schedules/**

        - id: appointment-service-surveys
          uri: http://localhost:8083
          predicates:
            - Path=/survey/**

app:
  security:
    whitelist:
      - path: /specialities
        methods: [GET]
      - path: /auth/login
        methods: [POST]
      - path: /auth/register
        methods: [POST]

management:
  endpoints:
    web:
      exposure:
        include: health, info